/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

/**
 *
 * @author Dialvec
 */
public class clientSearch extends javax.swing.JFrame {

    /**
     * Creates new form clientSearch
     */
    public clientSearch() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelTituloBuscarCliente = new javax.swing.JLabel();
        jLabelInstrBuscarCliente = new javax.swing.JLabel();
        jTextFieldBCNombre = new javax.swing.JTextField();
        jTextFieldBCAlias = new javax.swing.JTextField();
        jTextFieldBCApellido = new javax.swing.JTextField();
        jTextFieldBCEmail = new javax.swing.JTextField();
        jTextFieldBCCelular = new javax.swing.JTextField();
        jTextFieldBCDob = new javax.swing.JTextField();
        jButtonSearchClient = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabelTituloBuscarCliente.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelTituloBuscarCliente.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTituloBuscarCliente.setText("Buscar Cliente");

        jLabelInstrBuscarCliente.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabelInstrBuscarCliente.setText("Indique información del cliente que busca.");

        jTextFieldBCNombre.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextFieldBCNombre.setText("Nombre");

        jTextFieldBCAlias.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextFieldBCAlias.setText("Alias");

        jTextFieldBCApellido.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextFieldBCApellido.setText("Apellido");
        jTextFieldBCApellido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldBCApellidoActionPerformed(evt);
            }
        });

        jTextFieldBCEmail.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextFieldBCEmail.setText("e-mail");
        jTextFieldBCEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldBCEmailActionPerformed(evt);
            }
        });

        jTextFieldBCCelular.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextFieldBCCelular.setText("Celular");
        jTextFieldBCCelular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldBCCelularActionPerformed(evt);
            }
        });

        jTextFieldBCDob.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextFieldBCDob.setText("Fecha de nacimiento");
        jTextFieldBCDob.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldBCDobActionPerformed(evt);
            }
        });

        jButtonSearchClient.setBackground(javax.swing.UIManager.getDefaults().getColor("InternalFrame.activeTitleGradient"));
        jButtonSearchClient.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButtonSearchClient.setText("Buscar");
        jButtonSearchClient.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonSearchClient.setBorderPainted(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelInstrBuscarCliente)
                    .addComponent(jTextFieldBCNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldBCAlias, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTextFieldBCApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonSearchClient, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jTextFieldBCEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldBCCelular, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldBCDob, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelTituloBuscarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelTituloBuscarCliente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelInstrBuscarCliente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextFieldBCAlias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(jTextFieldBCNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldBCApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonSearchClient))
                .addGap(9, 9, 9)
                .addComponent(jTextFieldBCEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(jTextFieldBCCelular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(jTextFieldBCDob, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldBCApellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldBCApellidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldBCApellidoActionPerformed

    private void jTextFieldBCEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldBCEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldBCEmailActionPerformed

    private void jTextFieldBCCelularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldBCCelularActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldBCCelularActionPerformed

    private void jTextFieldBCDobActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldBCDobActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldBCDobActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(clientSearch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(clientSearch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(clientSearch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(clientSearch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new clientSearch().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonSearchClient;
    private javax.swing.JLabel jLabelInstrBuscarCliente;
    private javax.swing.JLabel jLabelTituloBuscarCliente;
    private javax.swing.JTextField jTextFieldBCAlias;
    private javax.swing.JTextField jTextFieldBCApellido;
    private javax.swing.JTextField jTextFieldBCCelular;
    private javax.swing.JTextField jTextFieldBCDob;
    private javax.swing.JTextField jTextFieldBCEmail;
    private javax.swing.JTextField jTextFieldBCNombre;
    // End of variables declaration//GEN-END:variables
}
