/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

/**
 *
 * @author Dialvec
 */
public class inentionSearch extends javax.swing.JFrame {

    /**
     * Creates new form clientSearch
     */
    public inentionSearch() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelTituloBuscarCliente = new javax.swing.JLabel();
        jLabelInstrBuscarCliente = new javax.swing.JLabel();
        jTextFieldBINombre = new javax.swing.JTextField();
        jTextFieldBIAlias = new javax.swing.JTextField();
        jTextFieldBIApellido = new javax.swing.JTextField();
        jTextFieldBIFabricante = new javax.swing.JTextField();
        jButtonSearchClient = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabelTituloBuscarCliente.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelTituloBuscarCliente.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTituloBuscarCliente.setText("Buscar Intención de Compra");

        jLabelInstrBuscarCliente.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabelInstrBuscarCliente.setText("Indique información de la búsqueda.");

        jTextFieldBINombre.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextFieldBINombre.setText("Nombre cliente");

        jTextFieldBIAlias.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextFieldBIAlias.setText("Alias cliente");
        jTextFieldBIAlias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldBIAliasActionPerformed(evt);
            }
        });

        jTextFieldBIApellido.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextFieldBIApellido.setText("Apellido cliente");
        jTextFieldBIApellido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldBIApellidoActionPerformed(evt);
            }
        });

        jTextFieldBIFabricante.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextFieldBIFabricante.setText("fabricante vehículo");
        jTextFieldBIFabricante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldBIFabricanteActionPerformed(evt);
            }
        });

        jButtonSearchClient.setBackground(javax.swing.UIManager.getDefaults().getColor("InternalFrame.activeTitleGradient"));
        jButtonSearchClient.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButtonSearchClient.setText("Buscar");
        jButtonSearchClient.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonSearchClient.setBorderPainted(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelInstrBuscarCliente)
                    .addComponent(jTextFieldBIAlias, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldBIFabricante, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelTituloBuscarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldBINombre, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldBIApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonSearchClient, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelTituloBuscarCliente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelInstrBuscarCliente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextFieldBIAlias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(jTextFieldBINombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11)
                        .addComponent(jTextFieldBIApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jButtonSearchClient)))
                .addGap(9, 9, 9)
                .addComponent(jTextFieldBIFabricante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldBIApellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldBIApellidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldBIApellidoActionPerformed

    private void jTextFieldBIFabricanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldBIFabricanteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldBIFabricanteActionPerformed

    private void jTextFieldBIAliasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldBIAliasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldBIAliasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(inentionSearch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(inentionSearch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(inentionSearch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(inentionSearch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new inentionSearch().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonSearchClient;
    private javax.swing.JLabel jLabelInstrBuscarCliente;
    private javax.swing.JLabel jLabelTituloBuscarCliente;
    private javax.swing.JTextField jTextFieldBIAlias;
    private javax.swing.JTextField jTextFieldBIApellido;
    private javax.swing.JTextField jTextFieldBIFabricante;
    private javax.swing.JTextField jTextFieldBINombre;
    // End of variables declaration//GEN-END:variables
}
