/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

/**
 *
 * @author Dialvec
 */
public class vehiculoSearch extends javax.swing.JFrame {

    /**
     * Creates new form clientSearch
     */
    public vehiculoSearch() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelTituloBuscarCliente = new javax.swing.JLabel();
        jLabelInstrBuscarCliente = new javax.swing.JLabel();
        jTextFieldBVPrecio = new javax.swing.JTextField();
        jTextFieldBVFabricante = new javax.swing.JTextField();
        jTextFieldBVBanio = new javax.swing.JTextField();
        jTextFieldBVMProveedor = new javax.swing.JTextField();
        jButtonSearchBicycle = new javax.swing.JButton();
        jLabelBicicletas = new javax.swing.JLabel();
        jTextFieldBVMAutonomia = new javax.swing.JTextField();
        jLabelBicicletas1 = new javax.swing.JLabel();
        jButtonSearchBicycle1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabelTituloBuscarCliente.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelTituloBuscarCliente.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTituloBuscarCliente.setText("Buscar Vehículo");

        jLabelInstrBuscarCliente.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabelInstrBuscarCliente.setText("Indique información de vehículo que busca");

        jTextFieldBVPrecio.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextFieldBVPrecio.setText("precio");

        jTextFieldBVFabricante.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextFieldBVFabricante.setText("fabricante");
        jTextFieldBVFabricante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldBVFabricanteActionPerformed(evt);
            }
        });

        jTextFieldBVBanio.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextFieldBVBanio.setText("año de fabricación");
        jTextFieldBVBanio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldBVBanioActionPerformed(evt);
            }
        });

        jTextFieldBVMProveedor.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextFieldBVMProveedor.setText("proveedor del motor");
        jTextFieldBVMProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldBVMProveedorActionPerformed(evt);
            }
        });

        jButtonSearchBicycle.setBackground(javax.swing.UIManager.getDefaults().getColor("InternalFrame.activeTitleGradient"));
        jButtonSearchBicycle.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButtonSearchBicycle.setText("Buscar Bicicleta");
        jButtonSearchBicycle.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonSearchBicycle.setBorderPainted(false);

        jLabelBicicletas.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelBicicletas.setText("Bicicletas");

        jTextFieldBVMAutonomia.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextFieldBVMAutonomia.setText("horas autonomía");
        jTextFieldBVMAutonomia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldBVMAutonomiaActionPerformed(evt);
            }
        });

        jLabelBicicletas1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelBicicletas1.setText("Motos Eléctricas");

        jButtonSearchBicycle1.setBackground(javax.swing.UIManager.getDefaults().getColor("InternalFrame.activeTitleGradient"));
        jButtonSearchBicycle1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButtonSearchBicycle1.setText("Buscar Moto");
        jButtonSearchBicycle1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonSearchBicycle1.setBorderPainted(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelTituloBuscarCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelInstrBuscarCliente)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(jLabelBicicletas)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabelBicicletas1)
                        .addGap(27, 27, 27))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jButtonSearchBicycle, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 63, Short.MAX_VALUE)
                        .addComponent(jButtonSearchBicycle1, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(17, 17, 17))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTextFieldBVBanio, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldBVMProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldBVMAutonomia, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(97, 97, 97)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldBVFabricante, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldBVPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelTituloBuscarCliente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelInstrBuscarCliente)
                .addGap(18, 18, 18)
                .addComponent(jTextFieldBVFabricante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextFieldBVPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelBicicletas)
                    .addComponent(jLabelBicicletas1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldBVBanio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldBVMProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextFieldBVMAutonomia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonSearchBicycle)
                    .addComponent(jButtonSearchBicycle1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldBVBanioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldBVBanioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldBVBanioActionPerformed

    private void jTextFieldBVMProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldBVMProveedorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldBVMProveedorActionPerformed

    private void jTextFieldBVFabricanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldBVFabricanteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldBVFabricanteActionPerformed

    private void jTextFieldBVMAutonomiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldBVMAutonomiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldBVMAutonomiaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(vehiculoSearch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(vehiculoSearch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(vehiculoSearch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(vehiculoSearch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new vehiculoSearch().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonSearchBicycle;
    private javax.swing.JButton jButtonSearchBicycle1;
    private javax.swing.JLabel jLabelBicicletas;
    private javax.swing.JLabel jLabelBicicletas1;
    private javax.swing.JLabel jLabelInstrBuscarCliente;
    private javax.swing.JLabel jLabelTituloBuscarCliente;
    private javax.swing.JTextField jTextFieldBVBanio;
    private javax.swing.JTextField jTextFieldBVFabricante;
    private javax.swing.JTextField jTextFieldBVMAutonomia;
    private javax.swing.JTextField jTextFieldBVMProveedor;
    private javax.swing.JTextField jTextFieldBVPrecio;
    // End of variables declaration//GEN-END:variables
}
