/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

/**
 *
 * @author Dialvec
 */
public class vehiculoModify extends javax.swing.JFrame {

    /**
     * Creates new form clientSearch
     */
    public vehiculoModify() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelTituloBuscarCliente = new javax.swing.JLabel();
        jLabelInstrBuscarCliente = new javax.swing.JLabel();
        jTextFieldBVPrecio = new javax.swing.JTextField();
        jTextFieldBVFabricante = new javax.swing.JTextField();
        jTextFieldBVBanio = new javax.swing.JTextField();
        jTextFieldBVMProveedor = new javax.swing.JTextField();
        jButtonActionMotorcycle = new javax.swing.JButton();
        jLabelBicicletas = new javax.swing.JLabel();
        jTextFieldBVMAutonomia = new javax.swing.JTextField();
        jLabelMotos = new javax.swing.JLabel();
        jLabelFabricante = new javax.swing.JLabel();
        jLabelPrecio = new javax.swing.JLabel();
        jLabelAnioFabrica = new javax.swing.JLabel();
        jLabelProveedor = new javax.swing.JLabel();
        jLabelAutonomia = new javax.swing.JLabel();
        jButtonActionBicycle = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabelTituloBuscarCliente.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelTituloBuscarCliente.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTituloBuscarCliente.setText("Crear/Editar Vehículo");

        jLabelInstrBuscarCliente.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabelInstrBuscarCliente.setText("Indique información de vehículo a editar");

        jTextFieldBVPrecio.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jTextFieldBVFabricante.setEditable(false);
        jTextFieldBVFabricante.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextFieldBVFabricante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldBVFabricanteActionPerformed(evt);
            }
        });

        jTextFieldBVBanio.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextFieldBVBanio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldBVBanioActionPerformed(evt);
            }
        });

        jTextFieldBVMProveedor.setEditable(false);
        jTextFieldBVMProveedor.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextFieldBVMProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldBVMProveedorActionPerformed(evt);
            }
        });

        jButtonActionMotorcycle.setBackground(javax.swing.UIManager.getDefaults().getColor("InternalFrame.activeTitleGradient"));
        jButtonActionMotorcycle.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButtonActionMotorcycle.setText("Motocicleta");
        jButtonActionMotorcycle.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonActionMotorcycle.setBorderPainted(false);

        jLabelBicicletas.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelBicicletas.setText("Bicicletas");

        jTextFieldBVMAutonomia.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextFieldBVMAutonomia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldBVMAutonomiaActionPerformed(evt);
            }
        });

        jLabelMotos.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelMotos.setText("Motos Eléctricas");

        jLabelFabricante.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelFabricante.setText("Fabricante");

        jLabelPrecio.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelPrecio.setText("Precio");

        jLabelAnioFabrica.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelAnioFabrica.setText("Año fabricación");

        jLabelProveedor.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelProveedor.setText("Proveedor motor");

        jLabelAutonomia.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelAutonomia.setText("Horas autonomia");

        jButtonActionBicycle.setBackground(javax.swing.UIManager.getDefaults().getColor("InternalFrame.activeTitleGradient"));
        jButtonActionBicycle.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButtonActionBicycle.setText("Bicicleta");
        jButtonActionBicycle.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonActionBicycle.setBorderPainted(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabelBicicletas)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelTituloBuscarCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelInstrBuscarCliente)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabelProveedor)
                                            .addComponent(jLabelAutonomia)
                                            .addComponent(jLabelFabricante)
                                            .addComponent(jLabelAnioFabrica)
                                            .addComponent(jLabelPrecio))
                                        .addGap(33, 33, 33)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jTextFieldBVBanio, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jTextFieldBVPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jTextFieldBVFabricante, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jTextFieldBVMAutonomia, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jTextFieldBVMProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())))
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabelMotos)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButtonActionBicycle, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonActionMotorcycle, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelTituloBuscarCliente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelInstrBuscarCliente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldBVFabricante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelFabricante))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldBVPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelPrecio))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelBicicletas)
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldBVBanio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelAnioFabrica))
                .addGap(22, 22, 22)
                .addComponent(jLabelMotos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldBVMProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelProveedor))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldBVMAutonomia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelAutonomia))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonActionBicycle)
                    .addComponent(jButtonActionMotorcycle))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldBVBanioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldBVBanioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldBVBanioActionPerformed

    private void jTextFieldBVMProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldBVMProveedorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldBVMProveedorActionPerformed

    private void jTextFieldBVFabricanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldBVFabricanteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldBVFabricanteActionPerformed

    private void jTextFieldBVMAutonomiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldBVMAutonomiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldBVMAutonomiaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(vehiculoModify.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(vehiculoModify.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(vehiculoModify.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(vehiculoModify.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new vehiculoModify().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonActionBicycle;
    private javax.swing.JButton jButtonActionMotorcycle;
    private javax.swing.JLabel jLabelAnioFabrica;
    private javax.swing.JLabel jLabelAutonomia;
    private javax.swing.JLabel jLabelBicicletas;
    private javax.swing.JLabel jLabelFabricante;
    private javax.swing.JLabel jLabelInstrBuscarCliente;
    private javax.swing.JLabel jLabelMotos;
    private javax.swing.JLabel jLabelPrecio;
    private javax.swing.JLabel jLabelProveedor;
    private javax.swing.JLabel jLabelTituloBuscarCliente;
    private javax.swing.JTextField jTextFieldBVBanio;
    private javax.swing.JTextField jTextFieldBVFabricante;
    private javax.swing.JTextField jTextFieldBVMAutonomia;
    private javax.swing.JTextField jTextFieldBVMProveedor;
    private javax.swing.JTextField jTextFieldBVPrecio;
    // End of variables declaration//GEN-END:variables
}
